(require 'iswitchb)
(iswitchb-mode 1)
(require 'filecache)
(load "iswitchb-fc")
(add-to-list 'iswitchb-buffer-ignore "*Messages*")
(add-to-list 'iswitchb-buffer-ignore "*Backtrace")
(add-to-list 'iswitchb-buffer-ignore "*Quail Com")
(add-to-list 'iswitchb-buffer-ignore "*Buffer")
(add-to-list 'iswitchb-buffer-ignore "*fsm-debug")
(add-to-list 'iswitchb-buffer-ignore "*Completions")
(add-to-list 'iswitchb-buffer-ignore "^[tT][aA][gG][sS]$")
(add-to-list 'iswitchb-buffer-ignore "*scratch*")
(add-to-list 'iswitchb-buffer-ignore "*Pymacs*")
(defun iswitchb-local-keys ()
  (mapc (lambda (K) 
           (let* ((key (car K)) (fun (cdr K)))
             (define-key iswitchb-mode-map (edmacro-parse-keys key) fun)))
           '(("<right>" . iswitchb-next-match)
             ("<left>"  . iswitchb-prev-match)
             ("<up>"    . ignore             )
             ("<down>"  . ignore             ))))
(add-hook 'iswitchb-define-mode-map-hook 'iswitchb-local-keys)

(global-set-key [f2] (lambda () (interactive) (iswitchb-buffer)))
