(require 'yasnippet)
(yas/initialize)
(setq yas/root-directory "~/.emacs.d/own_snippets")
(yas/load-directory "~/.emacs.d/packages/yasnippet/snippets")
(yas/load-directory yas/root-directory)
(setq yas/global-mode t)
